object Versions {
    const val jacksonJrVersion: String = "2.12.1"
    const val coroutinesVersion: String = "1.4.1"
    const val kotlinVersion: String = "1.5.10"
    const val mockkVersion: String = "1.10.3-jdk8"
    const val mockWSVersion: String = "4.4.0"
    const val robolectricVersion: String = "4.4"
    const val androidxTestVersion: String = "1.3.0"
    const val okHttpCmpVersion: String = "4.9.0"
    const val okHttpLatestVersion: String = "4.9.0"
    const val koinVersion: String = "3.2.0"
    const val androidxCoreVersion: String = "1.5.0"
    const val androidxAppcompatVersion: String = "1.3.0"
    const val materialVersion: String = "1.3.0"
    const val constraintLayoutVersion: String = "2.0.4"
    const val vectorDrawableVersion: String = "1.1.0"
    const val androidxLifecycleVersion: String = "2.3.1"
    const val sqlDelightVersion: String = "1.5.0"

}
