name: Feature tests
on:
  push:
    branches: [ "*tests*" ]
#    paths:
#      - '!README.md'
#      - '!release_note.txt'
#      - '!samples/nativemessage/*'

jobs:
  UI-and-Unit-test-cmplib:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: creating local.properties # this file is normally added to .gitignore
        run: touch local.properties
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Unit Tests
        run: ./gradlew cmplibrary:test
      - name: 'Publish Unit tests Report cmplibrary'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'unit-tests-report-v6'
          path: cmplibrary/build/reports/*
      - name: UI cmplibrary tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew cmplibrary:connectedAndroidTest
      - name: 'Publish UI cmplibrary Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'cmplibrary-test-report'
          path: cmplibrary/build/reports/androidTests/*