name: Instrumentation Test - Firebase Test Lab
on:
  push:
    branches: [ sp-7054-meta-base-config ]
#    paths:
#      - '!README.md'
#      - '!release_note.txt'
  #      - '!samples/nativemessage/*'
  pull_request:
    branches: [ sp-7054-meta-base-config ]
#    paths:
#      - '!README.md'
#      - '!samples/nativemessage/*'
jobs:
  ui-test-app:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: creating local.properties # this file is normally added to .gitignore
        run: touch local.properties
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Build test artifact
        run: |
          ./gradlew app:assembleDebug app:assembleDebugAndroidTest metaapp:assembleDebug metaapp:assembleDebugAndroidTest
          cp samples/app/build/outputs/apk/debug/app-debug.apk ./app-debug.apk
          cp samples/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk ./app-debug-androidTest.apk
          cp samples/metaapp/build/outputs/apk/debug/metaapp-debug.apk ./metaapp-debug.apk
          cp samples/metaapp/build/outputs/apk/androidTest/debug/metaapp-debug-androidTest.apk ./metaapp-debug-androidTest.apk
      - name: Run tests SampleApp on Firebase Test Lab
        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
        with:
          arg-spec: 'test_devices.yml:app-nexus_low_res'
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Run tests SampleApp on Firebase Test Lab
        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
        with:
          arg-spec: 'test_devices.yml:metaapp-nexus_low_res'
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}