name: SampleApp UI Tests
on:
  push:
    branches: [ develop ]
    paths:
      - '!README.md'
      - '!release_note.txt'
  pull_request:
    branches: [ develop ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  ui-test-app:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
          cache: gradle
      - name: creating local.properties # this file is normally added to .gitignore
        run: touch local.properties
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Build test artifact
        run: |
          ./gradlew app:assembleDebug app:assembleDebugAndroidTest
          cp samples/app/build/outputs/apk/debug/app-debug.apk ./app-debug.apk
          cp samples/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk ./app-debug-androidTest.apk
      - name: Run tests SampleApp on Firebase Test Lab
        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
        with:
          arg-spec: 'test_devices.yml:android-pixel-3-api28'
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}