name: Instrumentation Test - Firebase Test Lab
on:
  push:
    branches: [ sp-7068-firebase-test-lab ]
#    paths:
#      - '!README.md'
#      - '!release_note.txt'
#      - '!samples/nativemessage/*'
  pull_request:
    branches: [ develop ]
#    paths:
#      - '!README.md'
#      - '!samples/nativemessage/*'
jobs:
  ui-test-app-app:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: creating local.properties # this file is normally added to .gitignore
        run: touch local.properties
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Build test artifact
        run: ./gradlew app:assembleDebug app:assembleDebugAndroidTest
      - name: Instrumentation Test - Firebase Test Lab
        run: |
          export GRADLE_USER_HOME=$(pwd)/.gradle
          yes | sdkmanager --licenses && yes | sdkmanager --update
          wget --quiet --output-document=/tmp/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz
          mkdir -p /opt
          tar zxf /tmp/google-cloud-sdk.tar.gz --directory /opt
          /opt/google-cloud-sdk/install.sh --quiet
          source /opt/google-cloud-sdk/path.bash.inc
          gcloud components update
          gcloud config set project $PROJECT_ID
          echo $SERVICE_ACCOUNT_JSON > /tmp/service-account.json
          gcloud auth activate-service-account --key-file /tmp/service-account.json
          cp samples/app/build/outputs/apk/debug/app-debug.apk ./app-debug.apk
          cp samples/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk ./app-debug-androidTest.apk
          yes | sdkmanager --licenses && yes | sdkmanager --update
          gcloud firebase test android run   --type instrumentation   --app app-debug.apk   --test app-debug-androidTest.apk   --device model=walleye,version=28,locale=en,orientation=portrait
      - name: 'Publish Example-app Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'example-app-test-report'
          path: samples/app/build/reports/androidTests/*
