name: ARTIFACTS PROD/PREPROD
on:
  push:
    branches: [ preprod_workflow_disabled ]
#    paths:
#      - '!*.yml'
#      - '!README.md'
#      - '!CHANGELOG.md'
#      - '!samples/metaapp/gradle.properties'

jobs:
  build:
    name: Build APK prod/preprod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Bump versionCode
      id: bump
      run: |
        ./gradlew metaapp:bumpVersionCode
    - name: creating local.properties # this file is normally added to .gitignore
      run: touch local.properties
    - name: generating MetaApp build release
      id: buildArtifacts
      run: ./gradlew :metaapp:assemblePreprod :metaapp:assembleDebug
    - name: 'Publish MetaappPreprod artifact'
      if: always()
      uses: actions/upload-artifact@v2-preview
      with:
        name: 'MetaappPreprod'
        path: samples/metaapp/build/outputs/apk/preprod/metaapp-preprod.apk
    - name: 'Publish MetaappDebug artifact'
      if: always()
      uses: actions/upload-artifact@v2-preview
      with:
        name: 'MetaappDebug'
        path: samples/metaapp/build/outputs/apk/debug/metaapp-debug.apk
