name: Test
on:
  push:
    branches: [ develop ]
    paths:
      - '!README.md'
      - '!release_note.txt'
  pull_request:
    branches: [ develop ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  unit-test-cmplib:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - name: creating local.properties # this file is normally added to .gitignore
        run: touch local.properties
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Build test artifact
        run: ./gradlew cmplibrary:build
      - name: Unit Tests cmplibrary
        run: ./gradlew cmplibrary:test
  integration-tests-cmplib:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - run: rm -rf "$AGENT_TOOLSDIRECTORY" # free up space, impacts on the emulator being able to install
      - run: rm -rf /usr/share/dotnet # free up space, impacts on the emulator being able to install
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - name: creating local.properties # this file is normally added to .gitignore
        run: touch local.properties
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          profile: Pixel 5
          disable-animations: true
          disk-size: 6000M
          heap-size: 1024M
          emulator-options: -no-snapshot-save -no-window -noaudio -no-boot-anim -camera-back none
          script: ./gradlew cmplibrary:connectedAndroidTest
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: '**/build/reports/androidTests'
