name: Testing Matrix
on:
  push:
    branches: [ SP-5692_github_action_for_matrix_of_android_apis ]
  pull_request:
    branches: [ SP-5692_github_action_for_matrix_of_android_apis ]
jobs:
  ui-test-app:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [28, 29]
        target: [default, google_apis]
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: creating local.properties # this file is normally added to .gitignore
        run: touch local.properties
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: run Example app tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          script: ./gradlew app:connectedDebugAndroidTest
      - name: 'Testing Matrix : Publish Example-app Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'matrix: example-app-test-report'
          path: app/build/reports/androidTests/*
