name: Testing Matrix
on:
  push:
    branches: [ develop ]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: creating local.properties # this file is normally added to .gitignore
        run: touch local.properties
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: running unit tests
        run: ./gradlew test --quiet --build-cache
  ui-test-app:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        api-level: [30, 29, 28, 27, 26, 25, 24]
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: creating local.properties # this file is normally added to .gitignore
        run: touch local.properties
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: run Example app tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew app:connectedDebugAndroidTest
      - name: 'Publish Example-app Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'example-app-test-report'
          path: app/build/reports/androidTests/*
  ui-test-metaapp:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        api-level: [30, 29, 28, 27, 26, 25, 24]
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: creating local.properties # this file is normally added to .gitignore
        run: touch local.properties
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: run MetaApp tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew :metaapp:connectedDebugAndroidTest
      - name: 'Publish Metaapp Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'metaap-test-report'
          path: metaapp/build/reports/androidTests/*